default: &default
  adapter: postgresql
  host: db
  encoding: unicode
  username: root
  password: password
  pool: 5

development:
  <<: *default
  database: weather_development

test:
  <<: *default
  database: weather_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: weather_production